api:
  image: mcr.microsoft.com/playwright:bionic
  services:
    - postgres
  script:
    - packages/api/scripts/install-go-binaries-linux-amd64.sh
    - export PATH=$(pwd)/packages/api/bin:$PATH
    - createuser resourcesco-app
    - createdb --owner resourcesco-app resourcesco-app-test
    - yarn install
    - yarn api:test

app-e2e:
  image: mcr.microsoft.com/playwright:bionic
  services:
    - postgres
  script:
    - packages/api/scripts/install-go-binaries-linux-amd64.sh
    - export PATH=$(pwd)/packages/api/bin:$PATH
    - createuser resourcesco-app
    - createdb --owner resourcesco-app resourcesco-app-test
    - pushd packages/api && yarn migrate && popd
    - yarn install
    - yarn app:test
