api:
  image: mcr.microsoft.com/playwright:bionic
  services:
    - postgres
  variables:
    POSTGRES_DB: resourcesco-app-test
    POSTGRES_USER: resourcesco-app
    POSTGRES_PASSWORD: ramen32
    POSTGRES_HOST_AUTH_METHOD: trust
    NODE_TEST_DATABASE_URL: postgres://resourcesco-app:ramen32@postgres/resourcesco-app-test
    GO_TEST_DATABASE_URL: postgres://resourcesco-app:ramen32@postgres/resourcesco-app-test?sslmode=disable
  script:
    - apt-get install -y postgresql-client libpq-dev
    - packages/api/scripts/install-go-binaries-linux-amd64.sh
    - export PATH=$(pwd)/packages/api/bin:$PATH
    - yarn install
    - yarn api:test

gitea:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build packages/api/test/fixtures/gitea -t gitea-test
    - docker push $CI_REGISTRY/ResourcesCo/app/gitea-test:latest

app-e2e:
  image: mcr.microsoft.com/playwright:bionic
  services:
    - postgres
  artifacts:
    paths:
      - packages/app/__tests__/screenshots/
    expire_in: 1 week
  variables:
    POSTGRES_DB: resourcesco-app
    POSTGRES_USER: resourcesco-app
    POSTGRES_PASSWORD: ramen32
    POSTGRES_HOST_AUTH_METHOD: trust
    NODE_ENV: development
    APP_BASE: http://localhost:3000
    API_BASE: http://localhost:3001
    API_BASE_OAUTH: http://localhost:3002
    NODE_DATABASE_URL: postgres://resourcesco-app:ramen32@postgres/resourcesco-app
    GO_DATABASE_URL: postgres://resourcesco-app:ramen32@postgres/resourcesco-app?sslmode=disable
    NEXT_PUBLIC_APP_BASE: http://localhost:3000
    NEXT_PUBLIC_API_BASE: http://localhost:3001
    NEXT_PUBLIC_API_BASE_OAUTH: http://localhost:3002
  script:
    - apt-get install -y postgresql-client libpq-dev
    - packages/api/scripts/install-go-binaries-linux-amd64.sh
    - export PATH=$(pwd)/packages/api/bin:$PATH
    - yarn install
    - yarn build
    - cd packages/app && npm install playwright && cd ../..
    - yarn api:migrate
    - mv $PRIVATE_JWK_KEY_FILE packages/api/config/jwk/PrivateKeySet.json
    - mv $PUBLIC_JWK_KEY_FILE packages/api/config/jwk/PublicKeySet.json
    - yarn test:integration
