e2e:
  image: mcr.microsoft.com/playwright:bionic
  script:
    - apt-key adv --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
    - echo "deb http://repo.krakend.io/apt stable main" | tee /etc/apt/sources.list.d/krakend.list
    - apt-get update
    - apt-get install -y krakend
    - yarn install
    - yarn test
